### ISSUE TITLE
Feedback inside the Alexa app. 

### ISSUE THREAD

**Issue by burleanu** [originallyus/node-red-contrib-alexa-local#45] opened 2018-01-18 16:34 UTC
Hello, 
Thank you for creating this node. 
It is working very nice. 

Is there any chance of getting the feedback from the node inside the Alexa application? 
For example I'm thinking that you can put inside the configuration of the node inside node-red for the settings of increase/decrease value. This way can be used like now. I think... 
Also we can set how much means increase/decrease.
In my opinion I think is very helpful to have inside the Alexa app the feedback of what light is on. For example in case I forgot one open and I left my house. This way is not needed to create some other cloud app to check out the status. 
Of course if is not that difficult to make. 
If you don't want to modify that much the node maybe teach me how to change inside that "index. js" file what I need to  change to get there. 
Thanks again for the creation of this.

**Comment by torinnguyen** [comment] 2018-03-13 00:13
The on/off state shown in Alexa app has been fixed in 0.3.16 onwards.
However, the brightness shown in Alexa app will always be 49%. This is intentional.

You can make use of 'change_direction' and 'bri' output parameter & your own custom logic to define how much increase/decrease you want inside NodeRED. This can't be done via Alexa app.

**Comment by thePhilipp** [comment] 2018-03-27 21:16
Hello Torin,

I'm also looking for a way to show the status of a switch in the Alexa app. Is it possible to configure the input of the Alexa Node so that it can forward the mqtt feedback of a smart-switch to the Alexa app?
Unfortunately, if I switch the switches over my Node Red Dashboard, I can not see it in the app.

regards
Philipp

**Comment by torinnguyen** [comment] 2018-04-04 05:36
@thePhilipp can you take a screenshot of your NodeRED flow? It should be already possible in the latest version of alexa node.

**Comment by torinnguyen** [comment] 2018-04-04 23:56
I've mentioned in the previous comment, this is already possible in the current version of the node.
The on/off state shown in Alexa app is updated corrected.
However, the brightness shown in Alexa app will always be 49%. **This is intentional, not a bug.*
Take a look https://youtu.be/a6hX_959ID8

The important thing is you need to enable Input Trigger option in Alexa node.
<img width="518" alt="input_trigger" src="https://user-images.githubusercontent.com/767320/38340583-6785cf64-389e-11e8-9ef0-a1363f53abfd.png">

**Closed by torinnguyen** 2018-04-04 23:56 UTC

**Comment by thePhilipp** [comment] 2018-04-05 04:07
I know this checkbox but If i enable the input trigger there is a infinite Loop because i have the dashboard Switch in my Flow. Ok, i will try another Set Up in my Flow and then report

**Comment by torinnguyen** [comment] 2018-04-05 11:08
i see. In that case, you can use a Function node **behind** Alexa node to do some filtering based on **topic** parameters to avoid infinite loop.

**Comment by thePhilipp** [comment] 2018-04-05 12:42
have you a example for me? Unfortunately, I have almost no idea of javascript

**Comment by thePhilipp** [comment] 2018-04-05 21:56
ok, i have a solution. It's not nice but it work. I block the infinite loop with two trigger nodes. The first one let the feedback from my Sonoffs pass one times and the second trigger-node reset the first one after 70 milliseconds. 
![flow_switch with alexa and feedback](https://user-images.githubusercontent.com/37850165/38393881-a5f4a46c-392c-11e8-92d1-f8ac1c39ad06.JPG)
![trigger1](https://user-images.githubusercontent.com/37850165/38393890-acd66644-392c-11e8-8f25-35cd2a7dbacf.JPG)
![trigger2](https://user-images.githubusercontent.com/37850165/38393899-b0dc1eaa-392c-11e8-940a-0ca0638d4897.JPG)

**Comment by torinnguyen** [comment] 2018-04-05 23:07
I have no problem using SONOFF + UI Switch with Alexa Node.
Both Alexa app & UI Switch are updated when I interact with UI Switch or issue voice commands.

Video showing no infinite loop http://take.ms/0D8bF

<img width="740" alt="node-red 2018-04-06 05-59-38" src="https://user-images.githubusercontent.com/767320/38396013-046353f8-3960-11e8-9aeb-40f13fbf0156.png">
